encyclopedia/urls.py
from django.urls import path
from . import views


app_name = 'wikipedia'
urlpatterns = [
    path('', views.index, name='index'),
    path('wiki/<title>', views.entries, name='page-name'),
    path('new_page', views.new_page, name='create-new-page'),
    path('wiki/<title>/edit', views.edit_page, name='edit-page'),
    path('wiki/<title>/delete', views.delete_page, name='delete-page'),
    path('random', views.random_page, name='random-page'),
    path('search', views.search, name='search')
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from markdown2 import Markdown
from . import util
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect
from random import *


class NewPageForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Add a title','class': 'new-page-title'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Add new content here', 'class': 'new-page-textarea'}))


def index(request):
    return render(request, 'encyclopedia/index.html', {
        'entries': util.list_entries()
    })


def entries(request, title):
    markdowner = Markdown()
    content = util.get_entry(title)

    if content == None:
        return render(request, 'encyclopedia/404.html', {'msg': 'Uh oh! Sorry, the page (' + title + ') you were looking for was not found.'})

    content = markdowner.convert(content)
    return render(request, 'encyclopedia/page.html', {
        'content': content, 'title': title
    })


def new_page(request):
    if request.method == 'POST':
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']

            entries = util.list_entries()

            for entry in entries:            
                if title.upper() == entry.upper():
                    return render(request, 'encyclopedia/404.html', {'msg': 'Uh oh! Sorry, the page (' + title + ') already exist with this title.'})
               
            content = form.cleaned_data['content']
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse('wikipedia:page-name',args=[title]))

    return render(request, 'encyclopedia/create_new_page.html', {'form': NewPageForm()})


def edit_page(request, title):
    content = util.get_entry(title)

    form = NewPageForm()
    form.fields['title'].initial = title
    form.fields['content'].initial = content

    if request.method == 'POST':
        form = NewPageForm(request.POST)

        if form.is_valid():
            entries = util.list_entries()

            for entry in entries:
                print(entry)
                # If only the page content edited but the title has kept
                if title == entry:
                    content = form.cleaned_data['content']
                    util.save_entry(title, content)  
                    return HttpResponseRedirect(reverse('wikipedia:page-name',args=[title]))
                # If title has changed, it'll delete and recreate the file with the new title
                elif title != entry:
                    util.delete_entry(title)

                    title = form.cleaned_data['title']
                    content = form.cleaned_data['content']
                    util.save_entry(title, content)  
                    return HttpResponseRedirect(reverse('wikipedia:page-name',args=[title]))

    return render(request, 'encyclopedia/edit_page.html', {'content': content, 'title': title, 'form': form})


def delete_page(request, title):
    util.delete_entry(title)
    return HttpResponseRedirect(reverse('wikipedia:index'))


def random_page(request):
    page_list = util.list_entries()

    # pick a random number from a list
    random_title = sample(page_list, 1)

    return HttpResponseRedirect(reverse('wikipedia:page-name',args=[random_title[0]]))


def search(request):
    page_list = util.list_entries()
    searched_string = request.GET.get('q', '').upper()
    page_found = []

    for page in page_list:
        if searched_string in page.upper():
            page_found.append(page)

    if len(page_found) == 1 and page_found[0].upper() == searched_string:
        return HttpResponseRedirect(reverse('wikipedia:page-name',args=[page_found[0]]))
    elif len(page_found) >= 1:
        return render(request, 'encyclopedia/search.html', {'entries': page_found, 'result': True})
    else:
        return render(request, 'encyclopedia/search.html', {'entries': page_found, 'result': False})

    return HttpResponseRedirect(reverse('wikipedia:index'))

encyclopedia/templates/encyclopedia/create_new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki - Create New Page
{% endblock %}

{% block body %}

    <div>
        <h1>Create New Page</h1>
        <hr>
        <form action="{% url 'wikipedia:create-new-page' %}" method="POST" class="new-page-form">
            {% csrf_token %}
            {% comment %}
            <textarea name='content' placeholder="Add new content here" rows="40" cols="40" style="height: 40vh; width: 80%;"></textarea>
            {% endcomment %}

            {{ form }}

            <p><input type='submit' value="Create new page"></p>
        </form>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki - Edit {{ title }}
{% endblock %}

{% block body %}

    <div>
        <h1>Edit page</h1>
        <hr>
        <form action="{% url 'wikipedia:edit-page' title %}" method="POST" class="new-page-form">
            {% csrf_token %}
            <h2>Title: {{ title }}</h2>
                {{ form }} 
           <p><input type='submit' value="Edit page"></p>
        </form>
        
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Welcome to Wiki Encyclopedia</h1>

    <ul>
        {% for page in entries %}

            <li><a href="{% url 'wikipedia:page-name' page %}">{{ page }}</a></li>

        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wikipedia:search' %}" method="GET">
                    <!-- {% csrf_token %} -->
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wikipedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wikipedia:create-new-page' %}">Create New Page</a> 
                </div>
                <div>
                    <a href="{% url 'wikipedia:random-page' %}">Random Page</a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki - {{ title }}
{% endblock %}

{% block body %}

    <div>
        <p><a href="{% url 'wikipedia:edit-page' title %}">Edit page</a> | <a href="{% url 'wikipedia:delete-page' title %}">Delete page</a></p>
        <h2>{{ title }}</h2>
        <hr>
        {{ content | safe }}
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    <hr>
    <ul>
        {% if result %}
            {% for page in entries %}

                <li><a href="{% url 'wikipedia:page-name' page %}">{{ page }}</a></li>

            {% endfor %}

        {% else %}
            <h2>No Result. Try Again.</h2>
        {% endif %}
    </ul>

{% endblock %}